"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-07

Hand-written (not autogenerated) to match db/models.py exactly — see
docs/context/02-domain-model.md for the shapes and docs/context/07-decisions.md
ADR-006/ADR-007 for why the schema looks like this.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "type",
            sa.Enum("lease_extraction", "photo_analysis", name="jobtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "processing", "done", "failed", name="jobstatus"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
    )

    op.create_table(
        "units",
        sa.Column("unit_id", sa.String(), primary_key=True),
        sa.Column("property_id", sa.String(), nullable=False),
        sa.Column("property_name", sa.String(), nullable=False),
        sa.Column("building_id", sa.String(), nullable=False),
        sa.Column("building_name", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("area_sqm", sa.Float(), nullable=False),
        sa.Column("parking_bay", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "occupied", name="unitstatus"),
            nullable=False,
        ),
    )

    op.create_table(
        "leases",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source_file_ref", sa.String(), nullable=False),
        sa.Column("unit_id", sa.String(), sa.ForeignKey("units.unit_id"), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column(
            "extraction_job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id"),
            nullable=True,
            unique=True,
        ),
        sa.Column("unit_match_accepted", sa.Boolean(), nullable=False, server_default="false"),
    )

    op.create_table(
        "lease_fields",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lease_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("leases.id"), nullable=False),
        sa.Column("field_name", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("high", "low", "not_found", name="confidence"),
            nullable=False,
        ),
        sa.Column("source_excerpt", sa.Text(), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum("pending", "accepted", "rejected", "edited", name="reviewstatus"),
            nullable=False,
        ),
        sa.Column("edited_value", postgresql.JSONB(), nullable=True),
    )
    op.create_index("ix_lease_fields_lease_id", "lease_fields", ["lease_id"])

    op.create_table(
        "flags",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lease_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("leases.id"), nullable=False),
        sa.Column("field_name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("high", "medium", "low", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "pending", "accepted", "rejected", "edited", name="reviewstatus", create_type=False
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_flags_lease_id", "flags", ["lease_id"])

    op.create_table(
        "rule_evaluations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("lease_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("leases.id"), nullable=False),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum("PASS", "FAIL", "NOT_DETERMINABLE", name="ruleverdict"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("source_field_refs", postgresql.JSONB(), nullable=False, server_default="[]"),
    )
    op.create_index("ix_rule_evaluations_lease_id", "rule_evaluations", ["lease_id"])

    op.create_table(
        "photo_reports",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("unit_id", sa.String(), sa.ForeignKey("units.unit_id"), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("photo_refs", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("condition_assessment", sa.Text(), nullable=True),
        sa.Column("detected_contents", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("damages", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column(
            "analysis_job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("jobs.id"),
            nullable=True,
            unique=True,
        ),
    )
    op.create_index("ix_photo_reports_unit_id", "photo_reports", ["unit_id"])

    op.create_table(
        "work_orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "photo_report_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("photo_reports.id"),
            nullable=False,
        ),
        sa.Column("unit_id", sa.String(), sa.ForeignKey("units.unit_id"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            postgresql.ENUM("high", "medium", "low", name="severity", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "review_status",
            postgresql.ENUM(
                "pending", "accepted", "rejected", "edited", name="reviewstatus", create_type=False
            ),
            nullable=False,
        ),
    )
    op.create_index("ix_work_orders_unit_id", "work_orders", ["unit_id"])
    op.create_index("ix_work_orders_photo_report_id", "work_orders", ["photo_report_id"])


def downgrade() -> None:
    op.drop_table("work_orders")
    op.drop_table("photo_reports")
    op.drop_table("rule_evaluations")
    op.drop_table("flags")
    op.drop_table("lease_fields")
    op.drop_table("leases")
    op.drop_table("units")
    op.drop_table("jobs")

    sa.Enum(name="reviewstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="severity").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="confidence").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="ruleverdict").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="unitstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="jobtype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="jobstatus").drop(op.get_bind(), checkfirst=True)
