"""Storage boundary — see ADR-008 in docs/context/07-decisions.md.

`save`/`read_bytes`/`read_text` deal in storage *refs* (opaque relative
keys), never filesystem paths directly — that's what makes swapping
LocalDiskStorage for a GCS/S3-backed implementation later a constructor
change, not a call-site change. Shared by backend/api (writes on upload) and
backend/worker (reads during processing) so both sides speak the same
interface.
"""

import uuid
from pathlib import Path, PurePosixPath
from typing import Protocol


class Storage(Protocol):
    def save(self, filename: str, content: bytes) -> str:
        """Persists `content`, returns a ref to pass back to read_* later."""
        ...

    def read_bytes(self, ref: str) -> bytes: ...

    def read_text(self, ref: str) -> str: ...


def _safe_basename(filename: str) -> str:
    """Strips any directory components (`../`, absolute paths, embedded
    separators) from a client-supplied filename before it's ever used to
    build a filesystem path. Without this, `save("../../etc/cron.d/x", ...)`
    would write outside `root` -- this was a real path-traversal bug caught
    in code review, not a hypothetical."""
    name = PurePosixPath(filename.replace("\\", "/")).name
    return name or "upload"


class LocalDiskStorage:
    def __init__(self, root: Path):
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, ref: str) -> Path:
        # Defense in depth: refs are always server-generated by save() and
        # never contain traversal sequences, but a resolved path outside
        # root is rejected outright rather than trusted implicitly.
        path = (self.root / ref).resolve()
        if self.root.resolve() not in path.parents and path != self.root.resolve():
            raise ValueError(f"Refusing to access path outside storage root: {ref!r}")
        return path

    def save(self, filename: str, content: bytes) -> str:
        ref = f"{uuid.uuid4()}_{_safe_basename(filename)}"
        self._resolve(ref).write_bytes(content)
        return ref

    def read_bytes(self, ref: str) -> bytes:
        return self._resolve(ref).read_bytes()

    def read_text(self, ref: str) -> str:
        return self._resolve(ref).read_text()
